### ISSUE TITLE
TODO, plans, discussions and thoughts.

### ISSUE THREAD

**Issue by twaik** [termux/termux-x11#38]
Hi. I know it is unmaintained. But if someone sees this issue and familiar with topics you can comment freely.
I have no enogh time to implement all of it. But you can help if you want.

Please, quote a topic you want to comment.

<details>
<summary>Using wlroots instead of existing Wayland server implementation.</summary>

Lorie's core is developed to be small and fast, but also it is buggy and ugly. I was not a good programmer when I wrote it and still not a good programmer to fix it. When I tried to use `wlroots` last time I failed because it did not support software rendering (GLES rendering in `wlroots` requires something that we can not reach in Android). Now we can try it.
</details>

<details>
<summary>Using libinput instead of existing implementation.</summary>

As I said before I am not a good programmer and used existing gesture parser as touchpad event controller. It has a lot of disadvantages and I prefer to replace it.
It needs superuser privilegies to manage `/dev/input/*` and `libevdev`+`libudev`+`libmtdev`. But we can try to replace all of dependencies with `libudev-stub` and other `stub`s. 

</details>

<details>
<summary>Hardware acceleration.</summary>

We can go on using Mesa software acceleration or try to adapt `android-emugl` to be used in both `termux-packages` and `termux-x11`. This way is longer.
</details>

<details>
<summary>Using USB and BT keyboards and mice.</summary>

It will be very helpful in combination with external displays (using `Presentation API` or as `Secondary Home launcher`; using `Presentation API` is useful because we can output an image even if there is no hardware support of external displays, i.e. using `Miracast`, `Displaylink adapters` or `AOAv2`+TcpDisplay from AOSP tests). it is widely known that Android has it's own keyboard layout not compatible with GNU/Linux or Windows. Also Android does not let user apps to intercept input events. So we are screwed. Because we can not intercept Power button, Alt-Tab or other keys and key combinations. 
We can not open `/dev/input/*` directly. But we can ask Android to let us manage usb devices using `UsbManager API`. It can be used to manage usb device in extra thread or to get usb device fd that can be managed by libusb. We will need to parse HID request and answer them. Better then nothing.

**UPDATE:**
**Android does not allow apps to manage hid devices.** [link](https://cs.android.com/android/_/android/platform/frameworks/base/+/73a065a41f5ab51391f21f149eafa50dde341af1:services/usb/java/com/android/server/usb/UsbHostManager.java;l=285;drc=628590d7ec80e10a3fc24b1c18a1afb55cca10a8).
The only way is to read /dev/input/* but I still do not know how.
</details>

<details>
<summary>Android virtual keyboard input.</summary>

Input of special (Unicode) symbols and synbols of other layouts. It is bullshit. I am serious. It is not normal even if we handle only English layout. If we got special symbol we can only send Ctrl+Shift+U followed by symbol's code in hex and pray it was not sent from hardware keyboard. (KeyEvent.getScanCode() can very from device to device; I hope we can rely on InputDevice.isExternal() to check if it connected as USB or BT and InputDevice.isVirtual() to check if it is onscreen keyboard; there are exceptions, some android phones have hardware keyboard, like Pro1-X or Cosmo Communicator, alse there are some Android netbooks/laptops which have keyboard and touchpad too). If Android sends non-English symbol it sends `String`, not keycodes. We can not check if it was a symbol from special symbols tab or letter from another language layout, anyway it is sent as `String`. Everything we can do is to check if it is present in xkbcommon's layout. If it is not a part of language layout the only way to send it is to use `Ctrl+Shift+U` or to use clipboard.
We can not check what language layout user used when typed last letter, i.e. "A" which exists in most of Germanic languages and other languages (cyrillic A has different code in Unicode). It is a problem for all of languages because we can not predict what scancode we should send. 
For example user typed letter "Q". We do not know if user types text or plays. We can not check if user set English or French or Germanic layout. We can not check if it is AZERTY or QWERTY or ЙЦУКЕН or קראטון. We can try to change currect keyboard layout if we got some language specific symbol like Й, but what if it is common for a set of languages? Again. It is not a problem when user is just typing text. But what if he uses keyboard shortcuts or plays or does anything else???
It is a complete disaster.

</details>

<details>
<summary>Composition.</summary>

For now we can update only the whole display. We are uploading the whole display every single `XDamage` event we get. I mean it uploads the whole display even if the single pixel was changed. It is a waste of resources. We can try to listen every single X Window object and upload them one by one and then draw them on screen. This will give us a performance boost for a situation with a lot of small windows and will give us a base for hardware acceleration support.
</details>

<details>
<summary>Displaying modes.</summary>

We have just fullscreen and PiP mode. But what about implementing something like this?

https://user-images.githubusercontent.com/9674930/131396770-b8776497-3f0b-4ad6-9558-e6ff3eda44e8.mp4

That will let user switch between Android and GNU fast.

</details>

<details>
<summary>Hardware controls on external display.</summary>

Samsung Dex is not the best GUI I have ever seen but it has these important things. They can be implemented as X clients (indicators in system tray). I am pretty sure we can control Wifi, bt, sound and other stuff using public APIs on Android Activity side. I can implement something like `termux-api` working on top of Wayland socket. X clients can be implemented using C/GTK or C++/Qt. Still not sure about this.

 </details>

<details>
<summary>Some other TODO`s and task lists. WIP.</summary>

- [ ] For now when Lorie is not yet connected it shows blank black screen. I think it show show a message or connect instructions or something. Just like `XServer XSDL`.
- [ ] Hide virtual keyboard until Xwayland connects.
- [ ] Add a few shortcuts to launcher icon. 

</details>

Can you add something to this?

Maybe someone have other solutions?
Maybe I miss something?
Maybe you have some reference links?

You are welcome to discuss.

**Comment by suhan-paradkar** [comment]
Well.. About libinput and weston... I could cross compile them for termux... You can check them out in the release section of https://github.com/suhan-paradkar/tewmux-disabled

**Comment by RalfWerner** [comment]
Moin Twaik! Currently is the topic of [Fullsrceen mode](https://github.com/termux/termux-x11/issues/29#issuecomment-916850563) (included in your init-**X11**) and [ekeys->master](https://github.com/termux/termux-x11/pull/19#issuecomment-927022132) most importantly for me. I could not assign that to your list above. Note: For me you are a fantastic programmer

**Comment by twaik** [comment]
> About libinput and weston... I could cross compile them for termux... 

It is not a problem to crosscompile them. At all. It is a problem to make libinput work without root and access to /dev/input/* to work.
About Weston. It is better to forget it. It has no practical application. It can be used as a reference to develop your own compositor.
I talked about Wlroots. It can take care of all the Wayland protocol stuff and resource management and let us fix more interesting things. We will not implement something that is already implemented.

...

@RalfWerner I will a look at this later, after I get home to the real computer, not a Samsung Dex station.

**Comment by Yisus7u7** [comment]
I would very much like the full-screen mode to be added.

**Comment by etienne1911** [comment]
Would first point `wlroots` imply sway wm compatibilty?

I thought having wayland remote display would be very convenient as (quoting archwiki):

```
wlroots (used by sway) offers a VNC backend via wayvnc
```

**Comment by RalfWerner** [comment]
> to **Displaying modes**:

I use [OTS](https://github.com/termux/termux-float/issues/37#issuecomment-916777123) since there is **X11** and realized the change via an Extra Key (ekeys,EK). But mostly [PIP](https://user-images.githubusercontent.com/45426380/125047883-b241a300-e09f-11eb-9952-09bd1f22f905.mp4) where this is possible or [float](https://github.com/termux/termux-float/issues/37#issue-986858850).
> to **Some other TODO`s** and task lists. WIP...  **For now when Lorie is not yet connected it shows blank Black screen.**

**Black screen** is _not_ correct, as you could see in following two _landscape_ shots (Android 8 Huawei device):
![grafik](https://user-images.githubusercontent.com/45426380/135062486-3798808b-cb18-49ee-8bc7-7677f93590e6.png)
- shot one: The **Black screen (X11)** is reduced to the small area between Top-NavBar and the white screen`1)` with the same size as Extra-Keys below. And below this the _non-floating_ Hackers-Keyboard (tap on `KEYBOARD` - third EK from left).
- shot two: Same as one, but with an other _non-floating_ On-Screen-Keyboard. Here is the **X11** size reduced to _zero!_

When Fullscreen mode come back in Preferences, the Top and right (bottom in portrait) NavBars are hidden and increase **X11**
Is the Preference **Reseed Screen With Soft Keyboard is open** _on_, **X11** will _configure_`2)` to the  **Black screen** area
`1)` This is a bug on _this_ device (not on all devices but sometimes it overlaps), when show-Extra-Keys Preferences is switch on.
`2)` Same behavior as in VNC. The Window/Desktop Manager e.g. `fluxbox` have not more space as this .

**Comment by PokeyManatee4** [comment]
Its Not Unmaintaned Or It Is Not Worked  On Dumbass Hat

**Comment by twaik** [comment]
@PokeyManatee4 Github is not discord.

**Comment by twaik** [comment]
> Would first point wlroots imply sway wm compatibilty?

No. I wanna use wlroots as core library for better resource management. 
1. Lorie can handle Xwayland only and fails if anything else is trying to connect. Wlroots handle sother vompositors too and [maybe in the future] will be able to make X windows behave just like Android windows in multiwindow mode.
2. Lorie can not handle multiple Wayland clients (i.e. to fire custom commands, show/hide virtual keyboard, toggle fullscreen mode, call Lorie preferences, etc.)
3. Lorie's code needs refactoring and cleaning up. As I said before I am not good enough to write beautiful code.

@RalfWerner when I said "not connected" I meant the state when Xwayland did not connect to Lorie. I want to show something like splash screen until something connects to Lorie. 
About OTS. My version of termux-x11 (which does not need sharedUserId) will be able to fire termux's `RUN_COMMAND` to start user's script in `$PREFIX/libexec/termux-x11/termux-startx11`.

**Comment by twaik** [comment]
> Your points 1.+2. above I did not understand. It works almost everything! Not with you? 

X clients do not connect to Lorie directly. They are connecting to Xwayland, not Lorie. And Lorie has some bugs I can not fix.

> Just my thoughts! The two shots above I have made without Termux start but with ekeys branch

I think it should start with hidden virtual and extra keyboards. I'll fix it in the future.

> Where can I find the ones, did you replace Lorie there and how do you treat the joint-extra-keys?

You can find it in the corresponding pull request. But it needs special package which is not in termux repos yet.

> You are good enough*)! Android has no window mannager but some devices like my SM* have PiP in the OS, which is not comparable to the function of @suhan-paradkar and also not with MS-Windows or X11/Xorg.

<details>
<summary>Not right.</summary>

![Screenshot_20210929-124402_Chrome](https://user-images.githubusercontent.com/9674930/135245860-b45cbf0f-82d0-4ad2-b7e2-3e8608dbbac0.jpg)

</details>

Modern Android has multiwindow mode (you can see it in the pinned screenshot). Also it has PiP and Overlay Windows which can be used to simulate multiwindow even on outdated devices.

**Comment by RalfWerner** [comment]
>1: X clients do not connect to Lorie directly... 2: And Lorie has some bugs I can not fix

1: I know but X-protocol is correct - only that count! 2: Key-state and **FM** you*ve already **fixed** in your init-X11 3 years ago!
> I think it should start with hidden virtual and extra keyboards. I'll fix it in the future.

That is decision of Preferences and this could simply open by `DRAWER` only update of _decision_ actually not works
> Modern Android has multiwindow mode (you can see it in the pinned screenshot). Also it has PiP and Overlay Windows which can be used to simulate multiwindow even on **outdated devices.**

In your shot is the same _"Picture"_ in Picture behavour as on my _modern_ `SM*` device but it only _looks like_ Window-Manager (is still Android 11) and could **not** replace the X-WM. I like it but how could I put it on _**outdated devices?**_

**Comment by twaik** [comment]
> 1: I know but X-protocol is correct - only that count!

Lorie does not handle any of X protocols.

> That is decision of Preferences and this could simply open by DRAWER only update of decision actually not works

There is no reason to show virtual keyboard when Xwayland (or any client) is not connected.It is useless here.

> In your shot is the same "Picture" in Picture behavour as on my modern SM* device but it only looks like Window-Manager (is still Android 11 and much better than TaskBar) and could not replace the X-WM. I like it but how could I put it on outdated devices?

1. Multiwindow mode means you can open some **Android apps/activities** on the same screen and move them.
2. Picture in Picture mode is a special type of multi-window mode mostly used for video playback. It lets the user watch a video in a small window pinned to a corner of the screen while navigating between apps or browsing content on the main screen.
It can interact with activity programmatically (go fullscreen, let activity handle action buttions). But activity has no full control over this floating window. And can not receive touch ot other events from this window.
3. Floating/overlay window. That is floating window/surface which can be fully controlled by activity/service. It can have transparent background (i.e. for circle button), it can grab touch events or not, etc. That is the best choise for simulating WM for Android.

**Comment by RalfWerner** [comment]
> Lorie does not handle any of X protocols.

Since neither I nor you have claimed, but together with Xwayland, X11 behaves like any other XServer (manage _X protocols_) Inclusive Generic Events. So **X11** is far superior all the other Android-Xservers I know and has a fantastic performance.
> There is no reason to show virtual keyboard when Xwayland (or any client) is not connected.It is useless here.

I think we are talking about different things. Without OS-KB (virtual) or additional hardware, I could not use most XClients.

**To 1.**: I call that [PiP](https://github.com/RalfWerner/integrated-process/issues/2#issuecomment-733700709) or _in Pop View_ (Samsung). **To 2.**: is @suhan-paradkar [PiP](https://github.com/termux/termux-x11/pull/19#issuecomment-907666913) choice. Unfortunately, he has [deleted](https://github.com/WMCB-Tech/termux-x11/discussions/4#discussion-3557430) the check documentation. The conclusion (_unusable_ for work) remains. **To 3.**: You describe shortly what I've checked also but ...
> That is the best choice for simulating WM for Android.

I like to work with PiP, but do not share your statement for several reasons:
- All Window/Desktop Manager from the X11-repo and distros are far superior to PiP
- These are further developed and are identical on all Linux devices available and _in Pop view_ is only available on few devices
- I do not need a **WM** on Android and X11 also works [in PiP](https://user-images.githubusercontent.com/45426380/125047883-b241a300-e09f-11eb-9952-09bd1f22f905.mp4) as opposed to other Xservers. For my checks I use sometimes very simple **WM** like `fluxbox, openbox`, which manage _Workspaces_ and could easy turn on/off (I have that in EK as Key)
- For me the most important reason is _not a loss of functions_, just because I have _another device._ The extension of finger- and pen-work is then a profit and _thanks to your work_, I've already a lot of progress.

**Comment by twaik** [comment]
> I think we are talking about different things. Without OS-KB (virtual) or additional hardware, I could not use most XClients.

Exactly!!! When there is no XClients there is no reason to show keyboard! When user needs a keyboard he can call it using Android's back button...

> I like to work with PiP, but do not share your statement for several reasons:

PiP is not the only option. Watch some videos about Samsung Dex. It is not a replacement for PiP, that is different option which can be used separately. You are not forced to use it when it will be available. 
And I am tired discussing it.

**Comment by PokeyManatee4** [comment]
Im Suing Termux

**Comment by PokeyManatee4** [comment]
Cause Im Done

**Comment by Yisus7u7** [comment]
> Im Done With Termux Unfriendly Staff

What?

**Comment by PokeyManatee4** [comment]
*The Staff Are So Unfriendly.*

**Comment by Yisus7u7** [comment]
> _The Staff Are So Unfriendly._

What are you talking about?

**Comment by PokeyManatee4** [comment]
*![bitmoji](https://sdk.bitmoji.com/render/panel/b6d0de0a-0762-418e-9db2-b84c3ef51251-11611bb8-08a0-4a48-a006-f38848586588-v1.png?transparent=1&palette=1&width=246)BRUH*![bitmoji](https://sdk.bitmoji.com/render/panel/b6d0de0a-0762-418e-9db2-b84c3ef51251-11611bb8-08a0-4a48-a006-f38848586588-v1.png?transparent=1&palette=1&width=246)

**Comment by WMCB-Tech** [comment]
@PokeyManatee4 Please keep in mind that GitHub is a collaboration platform and not discord or telegram where you can bruh things about especially at Termux organization. your comments are unhelpful and meaningless and github isn't meant for that. it would be helpful if commenting your specific issue and not ranting that Termux staff isn't helpful

**Comment by RalfWerner** [comment]
> Exactly!!! When there is no XClients

I think we are **still** talking about different things! **XClients** are `fluxbox,aterm,xfce ...` and all other from _x11-repo_ and Self-made. **XServer** _here_ is **X11** but could also be **Xvnc** or **X** on PC. I hope we agree, that `aterm` _without_ Keyboard makes no sense. If you did not like the terms, we can use others. Make a suggestion.
> PiP is not the only option. Watch some videos about Samsung Dex.

I've the SM-P610 since one year (like it) and of course, I have viewed documentation and videos. You hopefully my above too and recognize your shot. I read also all Android 11 devices should be able to do this. Practical that s not.

I did not talk about an **option** at PiP, although you did not quite wrong. Practical it's an option of the split function as you saw in my [video](https://user-images.githubusercontent.com/45426380/125047883-b241a300-e09f-11eb-9952-09bd1f22f905.mp4). My **several reasons** still apply. You're **tired discussing it.** Apply that also to **X11**, than we should do it.

**Comment by bb010g** [comment]
Perhaps this app could utilize Waypipe? https://gitlab.freedesktop.org/mstoeckl/waypipe/

This lets users choose their compositor while still being pretty performant.

**Comment by bb010g** [comment]
@twaik I mean that Termux:X11 could become an app that starts up a Waypipe instance for a Wayland-using executable in Termux, and that would allow it to drop the XWayland constraint & some of the current implemention.

If you want XWayland with Waypipe, launch an X11 client with it.

**Comment by twaik** [comment]
Xwayland is the only app that Lorie can handle.

**Comment by twaik** [comment]
@bb010g I did not mean I do not want to drop Xwayland constraint, I meant Lorie was designed as minimal backend handling Xwayland.

**Comment by RalfWerner** [comment]
Unfortunately I've no success to start XClient=`fluxbox`, with and your currend _build_ (version 9). Your changed start description in README (`Xwayland` _replaced by_ `termux-x11`). All possible permissions in Termux and X11 I've _allowed_ and stored in `*properties` the line `allow-external-apps=true`. Result:
- After App-Start, the Process (PID2=`com.termux.x11`) is _not_ displayed (`ps`) as _before_.
- The start `env DISPLAY=:0 fluxbox` stop with `Error: couldn't connect to XServer: 0`
- After 10 seconds (`Termux startx11`) the process `termux-x11` (PID3) is terminated.

_**What is wrong or missing?**_

**Comment by twaik** [comment]
> After App-Start, the Process (PID2=com.termux.x11) is not displayed (ps) as before.

Android hides it because it has different uid.

Try that 
```
rm -f $PREFIX/bin/x-session-manager
ln -s fluxbox $PREFIX/bin/x-session-manager
```

And then start `$PREFIX/libexec/termux-x11/termux-startx11`.

**Comment by RalfWerner** [comment]
Unfortunately, that did _not_ work. The Xwayland process (PID3) is missing and also _your both_ files:
`y=$PREFIX/libexec/termux-x11/termux-startx11` and `WM=$PREFIX/bin/x-session-manager` do _not_ exist in Termux and will not generated by `pkg in termux-x11`. The package `xwayland` (PID3 - **also hidden?**) and start of it, is _not_ longer needed in the new README. Instead start `$WM` (PID4) will immediately after `$y` (PID2)
> Android hides it because it has different uid.

This behaviour was typical in the last years for _your basic **X11**_. Only in your first attempt and previous version (8) show PID2. Therefore [OTS](https://github.com/termux/termux-float/issues/37#issuecomment-916777123) includes the PID3-loop (`-z "$(pgrep -o $X)"`) to check PID2-start indirect. So again: _**What is wrong or missing?**_

**Comment by twaik** [comment]
> y=$PREFIX/libexec/termux-x11/termux-startx11 and WM=$PREFIX/bin/x-session-manager do not exist in Termux


Did you install companion package from the last artifact?

**Comment by RalfWerner** [comment]
> Did you install companion package from the last artifact?

No! why should I? It is not under **Setup Instructions** and `pkg in xwayland` was alrady done for version 8!

I studied your 421 sources (both versions). There are three `Only` and the word `companion` is included in file `build_termux_package` as `#!/bin/bash` (one of two new files - this and `$y`).

If I'm not mistaken, this is a _package build_ for _**off** device._ And you mean a termux _newby_ would immediately recognize this and have an environment to **do** it when _he/she_ read **How does it work?**
But if that it's not the case, could you please rewrite the script to _build **on** device_ and extend the **Instruction** by this step?

**Comment by twaik** [comment]
A few updates.
About using USB HID devices (keyboard and mice). 
We were not able to open `/dev/input/*` and we are not able to open usb interfaces using UsbDeviceManager because HID devices are blacklisted. [link](https://cs.android.com/android/_/android/platform/frameworks/base/+/73a065a41f5ab51391f21f149eafa50dde341af1:services/usb/java/com/android/server/usb/UsbHostManager.java;l=285;drc=628590d7ec80e10a3fc24b1c18a1afb55cca10a8)
**There is no legit way to grab HID devices and prevent Android from handling them.** 
The only time I succeed to see HID in Usb device enumerator's output was when I tried external keyboard combined with smart card reader. This device had a few usb descriptors and only one of them was HID. Looks like Android lets app read devices which are not HID only. Are there Arduino guys who can find out how to make ordinary keyboard being read by Android app? I think we can try to make something like USB proxy which adds some non-HID useless descriptors to original device's descriptors list. Of cource it should not be mandatory, just an option for advanced users.


About Android 10's `Desktop Mode`.
I succeed to force Android to open an app on external display instead of launcher and seen a few things. 
1. Android locks/disables external display if main display is locked. External display is protected until you unlock the phone. I did not check what happens while using `Presentation API` (without forcing desktop mode on external display). 
2. There is no way to prevent navigation bar from being shown. I tried immersive and fullscreen modes, tried to hide navbar every 10 milliseconds, tried to create screen overlay in combination with immersive mode. All of it did not work. That means every time I/user tries to interact with bottom panel (i.e. taskbar) Android navigation bar appears.
3. Hardware mouse input always targets to external display. Hardware keyboard input always follows focus. I mean you can touch `TextView`, type something with hardware keyboard and then click a mouse and type something on external display.
4. Android always handles `Alt+Tab` and other keyboard shortcuts. If external display does not have handler for `Alt+Tab` it is handled on main display, even if main display is unfocused.
5. We can use Android 10 `Pointer Capture API` in combination with Immersive mode to prevent Android's navigation bar from being shown on screen. But anyway Android releases pointer capture every time an app loses focus. And android does not notify app if it has lost focus/pointer capture mode. 
6. Android opens apps on external screen even if nobody asks to do that... And I do not know a way to override it.
We can try to use `Presentation API` without forcing desktop mode on external display but we will lose an ability to capture hardware keyboard and mouse at all.

I do not think using `SECONDARY_HOME` feature is great idea. 
I want to check what `AccessibilityService` can do. As I read it can intercept keyboard input (but do not know if it can intercept keyboard shortcuts like `Alt+Tab`). And I am sure it can not intercept mouse/touch events. I think we can show AccessibilityMenu button in navigation bar and show input surface to let user control external display. This input surface can use pointer capturing to handle mouse. 

Please, tell me if you know something else. Something that works...

**Comment by RalfWerner** [comment]
@taik these are many updates/concerns! Most I can **not**`*)` repeat, on the devices, I've used in recent years with your _basic **X11**_ version. However, I look at X11/XServer from the point of view of the XClient, which is different on other devices.

So I can use `nedit` (Ubuntu Distro in Termux) on the display of my PC (with mouse, touchpad and KB). But that has _nothing to do_ with **X11**. But if I mirrors the phone display with `scrcpy` or _TeamViewer_ on the same display, then already. USB I rarely used but BT (Blue Tooth is like USB) also with a few problems and none with CTRL/ALT etc.

`*)` So if you reactivate _Fullscreen Mode_ from your _basic app_, the [problem](https://github.com/termux/termux-x11/issues/29#issuecomment-916850563) with the Nav bars is solved (not EK/Reseed). I used this app as an [example](https://github.com/termux/termux-app/pull/1923#issuecomment-918252727), to show how Termux could do that too.
